name: Test

on:
  pull_request_target:
    paths-ignore:
      - 'docs/**'
  merge_group:
  workflow_dispatch:

concurrency:
  group: test-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  validate-manifests:
    uses: ./.github/workflows/validate-manifests.yml

  unit-tests:
    uses: ./.github/workflows/test-unit.yml

  check-licenses:
    uses: ./.github/workflows/check-licenses.yml
